---
  version: '3'
  services:
# TODO: Find or Build a basic Jira Dockerfile
#    jira:
#      build:
#        context: ./jira
#      image: chippinkston/jira:${TAG}
#      environment: [
#        "VIRTUAL_HOST=jira.${DOMAIN}"
#     ]
#      networks: ['req']
#     container_name: req_jira


    confluence:
      build:
        context: ./confluence
      image: chippinkston/confluence:${TAG}
      environment: [
        "VIRTUAL_HOST=confluence.${DOMAIN}",
        "VIRTUAL_PORT=8090"
      ]
      ports:
        - "8090:8090"
        - "8091:8091"
      volumes:
        - ./confluence/data:/var/atlassian/application-data/confluence
      networks: ['req']
     container_name: req_conf

    bitbucket:
      build:
        context: ./bitbucket
      image: chippinkston/bitbucket:${TAG}
      environment: [
        "VIRTUAL_HOST=bitbucket.${DOMAIN}",
        "VIRTUAL_PORT=7990"
      ]
      ports:
        - "7990:7990"
        - "7999:7999"
      volumes:
        - bitbucketVolume:/var/atlassian/application-data/bitbucket
      networks: ['req']
      container_name: req_bit

# TODO: Find or Build a basic Bamboo Dockerfile
#    bamboo:
#      build:
#        context: ./bamboo
#      image: chippinkston/bamboo:${TAG}
#      environment: [
#        "VIRTUAL_HOST=bamboo.${DOMAIN}"
#      ]
#      networks: ['req']
#      container_name: req_build

# TODO: Debug the issues this seems to cause with bitbucket
    postgres:
      build:
        context: ./postgres
      image: chippinkston/postgres:${TAG}
      environment: [
        "POSTGRES_PASSWORD: example",
        "VIRTUAL_HOST=postgres.${DOMAIN}",
        "VIRTUAL_PORT=5432"
      ]
      networks: ['req']
      container_name: req_db


  # nginx proxy - map ports to virtual hosts environmental variables:
  # reference -https://blog.florianlopes.io/host-multiple-websites-on-single-host-docker/
    nginx-proxy:
      build:
        context: ./nginx
      image: chippinkston/nginx:${TAG}
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      networks: ['req']
      container_name: req_nginx


  volumes:
    bitbucketVolume:
  networks: {req: {}}